# Generated by Django 5.1.3 on 2024-11-29 00:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shard',
            name='name',
            field=models.CharField(default='default_name', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shard',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
