# Generated by Django 5.1.3 on 2024-12-02 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lore',
            name='game_phase',
        ),
        migrations.AddField(
            model_name='lore',
            name='game_phases',
            field=models.ManyToManyField(to='character.gamephase'),
        ),
    ]
