# Generated by Django 5.1.3 on 2024-12-07 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0003_characternote'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='short_name',
            field=models.CharField(blank=True, max_length=4, unique=True),
        ),
    ]
